
# Reminder: variables are accessed via {{ site.myvariable }}.

### Website description
title: Sebastien Plat
url: "sebastienplat.github.io"  # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""                     # the subpath of your site, e.g. /blog
description:
  Personal blog discussing Data Science topics.

github_username:  sebastienplat
email: ""

### Setup
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown    # Kramdown is supported by Github

# site-wide variables
enable-mathjax: yes   # Mathjax setting
share: yes            # Change it to `no` to remove share buttons (setup in _includes)
 
# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# This defines how the URLs should look like
permalink: /blog/:title/

# Jekyll will load contents inside _xxx only if we tell it to
#include:
#  - _pages
  
# article series
collections_dir: articles

collections:
  data_science_101:
    output: true
    permalink: articles/:collection/:title

defaults:
  - scope:
      path: ""
      type: "data_science_101"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
